### PR TITLE
Fix error while inspecting

### LINKED ISSUE #6: An error occurred while Layout/SpaceInsideHashLiteralBraces cop was inspecting ...
After installing and do `pronto run`
I get:
```
An error occurred while Layout/SpaceInsideHashLiteralBraces cop was inspecting /path/to/file
```

doing
```
standardrb /path/to/file
```
and
```
rubocop /path/to/file
```
works as expected

### PR DESCRIPTION
**Pull request by epergo**
Should fix #6 

The change is basically the same as done in [pronto-rubocop](https://github.com/prontolabs/pronto-rubocop/pull/77)

### CODE REVIEW

File: lib/pronto/standardrb.rb [hunk 1]
```diff
@@ -7,7 +7,6 @@ module Pronto
   class Standardrb < Runner
     def run
       ruby_patches
-        .select { |patch| patch.additions > 0 }
```
Comment (epergo) [inline lib/pronto/standardrb.rb:10]: `ruby_patches` already filters by patches with additions https://github.com/prontolabs/pronto/blob/master/lib/pronto/runner.rb#L26

**Comment by julianrubisch** [comment]
Thank you!
